using Godot;

public class AutoGeneratedMap : Map
{
    private Generator generator;

<<<<<<< HEAD
    public AutoGeneratedMap(int width, int height, int unit, Node parentNode):
=======
    public AutoGeneratedMap(int width, int height, int unit, Node parentNode) :
>>>>>>> master
        base(width, height, unit, parentNode)
    {
        this.generator = new GeneratorV1(this, 10, 5, 10);
    }

    override public void Instance()
    {
        this.generator.GenerateMap();
        base.Instance();
    }
}
