using Godot;

public class Main : Node2D
{
	[Export]
	public PackedScene WallBlock;
	Map map;
	int MAP_SIZE = 30;
	int BLOCK_SIZE = 16;
	public static string SCENE_PATH = "res://Main.tscn";

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		map = new AutoGeneratedMap(MAP_SIZE, MAP_SIZE, BLOCK_SIZE, this);
		map.Instance();
	}

//  // Called every frame. 'delta' is the elapsed time since the previous frame.
//  public override void _Process(float delta)
//  {
//      
//  }
}
