using Godot;
using System.Diagnostics;

public class Main : Node2D
{
	Map map;
	int MAP_SIZE = 30;
	int BLOCK_SIZE = 16;
	public static string SCENE_PATH = "res://Main.tscn";
	Player player;
	GUI gui;

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		map = new AutoGeneratedMap(MAP_SIZE, MAP_SIZE, BLOCK_SIZE, this);
		map.Instance();
		player = GetNode<Player>("Player");
		gui = GetNode<GUI>("GUI");
	}    

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(float delta)
	{
		gui.SetHealthCounter(player.health);
		gui.SetEnemyCounter(CountEnemies());
		gui.SetMaxHealthCounter(player.maxHealth);
	}

	int CountEnemies()
	{
		int count = 0;
		foreach(var i in GetChildren())
		{
			Node node = (Node)i;
			var nodeClass = node.GetType().BaseType;
			if(nodeClass == typeof(Enemy))
			{
				count++;
			}
		}
		return count;
	}
}