name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     platform: [linux, windows]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
          dotnet_format_args: "./2DRogueLike.sln"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
